
name: geohasher
description: geohasher is a library for computing geohashes
version: 0.5.0
author: Levi Cook <levicook@gmail.com>
homepage: https://github.com/levicook/geohasher

dev_dependencies:
  args: ^1.5.2
  test: ^1.6.4

environment:
  sdk: '>=2.0.0 <3.0.0'
